/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.monkey;

import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class MonkeyMenu extends javax.swing.JFrame {

    /**
     * Creates new form MonkeyMenu
     */
    public MonkeyMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Monkey Menu");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtTiempoSalida1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSimulacion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCostoInventario = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCostoProduccion = new javax.swing.JTextField();
        txtCostoEmpaquetado = new javax.swing.JTextField();
        txtCostoSalida = new javax.swing.JTextField();
        txtTiempoInventario = new javax.swing.JTextField();
        txtTiempoProduccion = new javax.swing.JTextField();
        txtTiempoEmpaquetado = new javax.swing.JTextField();
        txtTiempoSalida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        txtTiempoSalida1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 219, 252));

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido a Monkey");

        btnSimulacion.setBackground(new java.awt.Color(237, 227, 225));
        btnSimulacion.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        btnSimulacion.setText("Iniciar simulación");
        btnSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulacionActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 211, 200));

        jLabel6.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        jLabel6.setText("Empaquetado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 211, 200));

        jLabel5.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        jLabel5.setText("Producción");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 211, 200));

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        jLabel4.setText("Inventario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        txtCostoInventario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 211, 200));

        jLabel7.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        jLabel7.setText("Salida");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        txtCostoProduccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCostoEmpaquetado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCostoEmpaquetado.setToolTipText("");

        txtCostoSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCostoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoSalidaActionPerformed(evt);
            }
        });

        txtTiempoInventario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTiempoProduccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTiempoEmpaquetado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempoEmpaquetado.setToolTipText("");

        txtTiempoSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoSalidaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 12)); // NOI18N
        jLabel2.setText("Tiempo (s)");

        jLabel3.setFont(new java.awt.Font("Ravie", 1, 12)); // NOI18N
        jLabel3.setText("Costo (Q/s)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTiempoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(txtCostoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTiempoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCostoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTiempoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCostoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTiempoInventario)
                                .addGap(46, 46, 46)
                                .addComponent(txtCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoSalidaActionPerformed

    private void txtTiempoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoSalidaActionPerformed

    private void btnSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulacionActionPerformed
        String strTiempoInventario = txtTiempoInventario.getText();
        String strCostoInventario = txtCostoInventario.getText();
        String strTiempoProduccion = txtTiempoProduccion.getText();
        String strCostoProduccion = txtCostoProduccion.getText();
        String strTiempoEmpaquetado = txtTiempoEmpaquetado.getText();
        String strCostoEmpaquetado = txtCostoEmpaquetado.getText();
        String strTiempoSalida = txtTiempoSalida.getText();
        String strCostoSalida = txtCostoSalida.getText();
        
        if(Restricciones.isNullOrEmpty(strTiempoInventario)) {
            JOptionPane.showMessageDialog(null, "El campo tiempo de inventario no puede ir vacio");
        }
        else if(Restricciones.isNullOrEmpty(strCostoInventario)) {
            JOptionPane.showMessageDialog(null, "El campo costo de inventario no puede ir vacio");
        }
        else if(Restricciones.isNullOrEmpty(strTiempoProduccion)) {
            JOptionPane.showMessageDialog(null, "El campo tiempo de producción no puede ir vacio");
        }
        else if(Restricciones.isNullOrEmpty(strCostoProduccion)) {
            JOptionPane.showMessageDialog(null, "El campo costo de producción no puede ir vacio");
        }
        else if(Restricciones.isNullOrEmpty(strTiempoEmpaquetado)) {
            JOptionPane.showMessageDialog(null, "El campo tiempo de empaquetado no puede ir vacio");
        }
        else if(Restricciones.isNullOrEmpty(strCostoEmpaquetado)) {
            JOptionPane.showMessageDialog(null, "El campo costo de empaquetado no puede ir vacio");
        }
        else if(Restricciones.isNullOrEmpty(strTiempoSalida)) {
            JOptionPane.showMessageDialog(null, "El campo tiempo de salida no puede ir vacio");
        }
        else if(Restricciones.isNullOrEmpty(strCostoSalida)) {
            JOptionPane.showMessageDialog(null, "El campo costo de salida no puede ir vacio");
        }
        
        else if(!Restricciones.soloNumeros(strTiempoInventario)){
            JOptionPane.showMessageDialog(null, "El campo tiempo de inventario solo acepta numeros enteros");
        }
        else if(!Restricciones.soloNumeros(strCostoInventario)){
            JOptionPane.showMessageDialog(null, "El campo costo de inventario solo acepta numeros enteros");
        }
        else if(!Restricciones.soloNumeros(strTiempoProduccion)){
            JOptionPane.showMessageDialog(null, "El campo tiempo de producción solo acepta numeros enteros");
        }
        else if(!Restricciones.soloNumeros(strCostoProduccion)){
            JOptionPane.showMessageDialog(null, "El campo costo de producción solo acepta numeros enteros");
        }
        else if(!Restricciones.soloNumeros(strTiempoEmpaquetado)){
            JOptionPane.showMessageDialog(null, "El campo tiempo de empaquetado solo acepta numeros enteros");
        }
        else if(!Restricciones.soloNumeros(strCostoEmpaquetado)){
            JOptionPane.showMessageDialog(null, "El campo costo de empaquetado solo acepta numeros enteros");
        }
        else if(!Restricciones.soloNumeros(strTiempoSalida)){
            JOptionPane.showMessageDialog(null, "El campo tiempo de salida solo acepta numeros enteros");
        }
        else if(!Restricciones.soloNumeros(strCostoSalida)){
            JOptionPane.showMessageDialog(null, "El campo costo de salida solo acepta numeros enteros");
        }
        
        else {
            VaraiblesGlobales.tiempoInventario = Integer.parseInt(strTiempoInventario);
            VaraiblesGlobales.costoInventario = Integer.parseInt(strTiempoInventario);
            VaraiblesGlobales.tiempoProduccion = Integer.parseInt(strTiempoProduccion);
            VaraiblesGlobales.costoProduccion = Integer.parseInt(strCostoProduccion);
            VaraiblesGlobales.tiempoEmpaquetado = Integer.parseInt(strTiempoEmpaquetado);
            VaraiblesGlobales.costoEmpaquetado = Integer.parseInt(strCostoEmpaquetado);
            VaraiblesGlobales.tiempoSalida = Integer.parseInt(strCostoSalida);
            VaraiblesGlobales.costoSalida = Integer.parseInt(strCostoSalida);
            
            VaraiblesGlobales.strTiempoInventario = strTiempoInventario;
            VaraiblesGlobales.strCostoInventario = strTiempoInventario;
            VaraiblesGlobales.strTiempoProduccion = strTiempoProduccion;
            VaraiblesGlobales.strCostoProduccion = strCostoProduccion;
            VaraiblesGlobales.strTiempoEmpaquetado = strTiempoEmpaquetado;
            VaraiblesGlobales.strCostoEmpaquetado = strCostoEmpaquetado;
            VaraiblesGlobales.strTiempoSalida = strCostoSalida;
            VaraiblesGlobales.strCostoSalida = strCostoSalida;
            
            
            MonkeySimulacion ventana = new MonkeySimulacion();
            this.setVisible(false);
            ventana.setVisible(true);
        }
        
    }//GEN-LAST:event_btnSimulacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonkeyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonkeyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonkeyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonkeyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonkeyMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimulacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCostoEmpaquetado;
    private javax.swing.JTextField txtCostoInventario;
    private javax.swing.JTextField txtCostoProduccion;
    private javax.swing.JTextField txtCostoSalida;
    private javax.swing.JTextField txtTiempoEmpaquetado;
    private javax.swing.JTextField txtTiempoInventario;
    private javax.swing.JTextField txtTiempoProduccion;
    private javax.swing.JTextField txtTiempoSalida;
    private javax.swing.JTextField txtTiempoSalida1;
    // End of variables declaration//GEN-END:variables
}
